### ISSUE TITLE
Is it possible to perfplot such funcs?

### ISSUE THREAD

**Issue by Merzix** [nschloe/perfplot#31]
```python
# perfplot for speedy solutions of task https://py.checkio.org/en/mission/flatten-dict/

import perfplot
from random import sample


source = [lambda k, v: {f'd{k}': v},
          lambda k, v: {f't{k}': {k: v}},
          lambda k, v: {f'i{k}': 'new'},
          lambda k, v: {},
          lambda k, v: v,
          lambda k, v: 'string',
]
def dict_generator(x):
    '''
    Generates a dicts with structure like:

    {"name": {
        "first": "One",
        "last": "Drone"
     },
     "job": "scout",
     "recent": {},
     "additional": {
        "place": {
            "zone": "1",
            "cell": "2"}
     }
    }
    '''
    return {i: sample(source, 1)[0](f'key{i}', sample(source, 1)[0](f'val{i}', 'val')) for i in range(x)}


def piotrnowak23(dictionary):
    result = {}

    def check_rec(d, temp):
        for k, v in d.items():
            if isinstance(v, dict):
                if len(v) == 0:
                    result[temp + '/' + str(k)] = ""
                    continue
                check_rec(v, temp + '/' + str(k))
            else:
                result[temp + '/' + str(k)] = v

    for key, value in dictionary.items():
        if isinstance(value, dict):
            if len(value) == 0:
                result[str(key)] = ""
                continue
            check_rec(value, str(key))
        else:
            result[key] = value

    return result


def ninth(dictionary, path=None):
    if path is None:
        path = []

    result = {}
    for key, value in dictionary.items():
        current_position = path + [key]
        current_path = '/'.join(current_position)
        if type(value) == str:
            result[current_path] = value
        elif not value:
            result[current_path] = ""
        else:
            result.update(ninth(value, path=current_position))
    return result


def surdum(d: dict, w: str=''):
    newd = {}
    for key in d:
        way = w
        way += key
        if type(d[key]) == dict:
            if len(d[key]) != 0:
                t = surdum(d[key], way + '/')
                newd.update(t)
            else:
                newd.update({way: ''})
        else:
            newd.update({way: d[key]})
    return newd


def vasiliykryuchkov(d, names=[]):
    temp = {}
    [temp.update({"/".join(names + [k]): v} if type(v) is str else
                 vasiliykryuchkov(v, names + [k]) if v else {"/".join(names + [k]):""})
        for k, v in d.items()]
    return temp


perfplot.show(
    setup=dict_generator,
    kernels=[
        piotrnowak23, ninth, surdum, vasiliykryuchkov
    ],
    n_range=[2**k for k in range(10)],
    logx=True,
    # logy=True,
    xlabel='rows'
)

```

```
(.venv3.6) merzix@Merzix-DESKTOP /mnt/DATA/PROJECTS/checkio $ python perfplot_testing.py 
  0%|                                                    | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):                        | 0/4 [00:00<?, ?it/s]
  File "perfplot_testing.py", line 89, in <module>
    xlabel='rows'
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/perfplot/main.py", line 210, in show
    out = bench(*args, **kwargs)
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/perfplot/main.py", line 128, in bench
    reference, kernel(data)
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/numpy/core/numeric.py", line 2270, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/numpy/core/numeric.py", line 2363, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
(.venv3.6) merzix@Merzix-DESKTOP /mnt/DATA/PROJECTS/checkio $
```

**Comment by nschloe** [comment]
The example is way to complicated. Reopen with a _minimal_ example that reproduces the error.

**Comment by Merzix** [comment]
```
# perfplot for speedy solutions of task https://py.checkio.org/en/mission/flatten-dict/

import perfplot


def fast(array):
    for x in array:
        if type(x) is list:
            yield from flat_list(x)
        else:
            yield x


def using_re(array): 
    yield from map(int, re.findall(r"-?\d+", str(array)))


def using_str(array):
    yield from [int(x) for x in [i.strip('[ ]') for i in str(array).split(',')] if x]


perfplot.show(
    setup=lambda x: {'name': x},  # or just empty dict
    kernels=[
        fast, using_re, using_str
    ],
    n_range=[2**k for k in range(10)],
    logx=True,
    # logy=True,
    xlabel='rows'
)

```

Minimal code, minimal example, but still the same Error
