### ISSUE TITLE
Is it possible to perfplot such funcs (minimal)?

### ISSUE THREAD

**Issue by Merzix** [nschloe/perfplot#32]
```python
# perfplot for speedy solutions of task https://py.checkio.org/en/mission/flatten-dict/

import perfplot


def surdum(d: dict, w: str=''):
    newd = {}
    for key in d:
        way = w
        way += key
        if type(d[key]) == dict:
            if len(d[key]) != 0:
                t = surdum(d[key], way + '/')
                newd.update(t)
            else:
                newd.update({way: ''})
        else:
            newd.update({way: d[key]})
    return newd


perfplot.show(
    setup=lambda x: {'name': x},  # or just empty dict
    kernels=[
        surdum
    ],
    n_range=[2**k for k in range(10)],
    logx=True,
    # logy=True,
    xlabel='rows'
)
```

Minimal code, minimal example, but still the same Error

```
Traceback (most recent call last):
  File "flatten_dict.py", line 28, in <module>
    xlabel='rows'
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/perfplot/main.py", line 210, in show
    out = bench(*args, **kwargs)
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/perfplot/main.py", line 128, in bench
    reference, kernel(data)
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/numpy/core/numeric.py", line 2270, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/mnt/DATA/PROJECTS/checkio/.venv3.6/lib/python3.6/site-packages/numpy/core/numeric.py", line 2363, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

```

**Comment by nschloe** [comment]
Ah yes. By default, perfplot checks that the results from all the function evaluations are equal. The default check fails here (since you're using dicts, Numpy arrays would be the usual thing). You can skip the check by supplying
```
equality_check=None
```
as an argument.

**Comment by Merzix** [comment]
Thanks a lot, it helped.
