### ISSUE TITLE
readme example fails with time_unit parameter

### ISSUE THREAD

**Issue by asongtoruin** [nschloe/perfplot#52]
The example provided in the readme fails if the `time_unit` line is commented out, e.g.

```python
import numpy
import perfplot

perfplot.show(
    setup=lambda n: numpy.random.rand(n),  # or simply setup=numpy.random.rand
    kernels=[
        lambda a: numpy.c_[a, a],
        lambda a: numpy.stack([a, a]).T,
        lambda a: numpy.vstack([a, a]).T,
        lambda a: numpy.column_stack([a, a]),
        lambda a: numpy.concatenate([a[:, None], a[:, None]], axis=1),
    ],
    labels=["c_", "stack", "vstack", "column_stack", "concat"],
    n_range=[2 ** k for k in range(15)],
    xlabel="len(a)",
    # More optional arguments with their default values:
    # title=None,
    # logx=False,
    # logy=False,
    # equality_check=numpy.allclose,  # set to None to disable "correctness" assertion
    # automatic_order=True,
    # colors=None,
    # target_time_per_measurement=1.0,
    time_unit="auto"  # set to one of ("s", "ms", "us", or "ns") to force plot units
)
```

Full error:
```
Traceback (most recent call last):
  File "issue_raiser.py", line 24, in <module>
    time_unit="auto"  # set to one of ("s", "ms", "us", or "ns") to force plot units
  File "C:\Anaconda3\envs\perfplots\lib\site-packages\perfplot\main.py", line 248, in show
    out = bench(*args, **kwargs)
TypeError: bench() got an unexpected keyword argument 'time_unit'
```

**Comment by nschloe** [comment]
Thanks for the report, fixed now.

**Comment by asongtoruin** [comment]
Much appreciated, thanks.
