### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by machinexa2** [nschloe/perfplot#85]
```py
import perfplot
from urllib.parse import quote as uurlencode
from faster_than_requests import urlencode as furlencode

def example_uurlencode(x):
    return uurlencode(x)

def example_furlencode(x):
    return furlencode(x, use_plus=False)

perfplot.show(
    setup=lambda n: "A"* n,
    kernels=[
        example_uurlencode,
        example_furlencode,
    ],
    n_range=[2 ** k for k in range(8)],
    xlabel="A string of length n",
)
```
Error: 
`TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

```
Traceback (most recent call last):
  File "PerfplotExample.py", line 11, in <module>
    perfplot.show(
  File "/usr/local/lib/python3.8/dist-packages/perfplot/main.py", line 333, in show
    out = bench(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/perfplot/main.py", line 222, in bench
    assert equality_check(
  File "<__array_function__ internals>", line 5, in allclose
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/numeric.py", line 2189, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 5, in isclose
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/numeric.py", line 2287, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by machinexa2** [comment]
Syntax from: https://stackoverflow.com/questions/952914/how-to-make-a-flat-list-out-of-list-of-lists?page=1&tab=votes#tab-top

**Comment by machinexa2** [comment]
IN your documentation lambda is given but in stackoverflow not, i am confused

**Comment by nschloe** [comment]
Just use `equality_check=None`. I've just improved the error message, too.

![out](https://user-images.githubusercontent.com/181628/97158589-eecfa780-1779-11eb-9b51-3c6c51125878.png)
